In [1]:
import numpy as np
arr= np.array([1, 2, 3, 4, 5])
print("Array: ",arr)

Array:  [1 2 3 4 5]


In [2]:
#shape, data type, size, and dimensions
print("Shape: ",arr.shape)
print("Data Type: ",arr.dtype)
print("Size: ",arr.size)
print("Dimensions: ",arr.ndim)

Shape:  (5,)
Data Type:  int64
Size:  5
Dimensions:  1


In [3]:
#zero array
zero_arr = np.zeros((3, 4))
print("Zero Array: \n", zero_arr)

#ones array
ones_arr = np.ones((2, 5))
print("Ones Array: \n", ones_arr)

#random array
random_arr = np.random.rand(3, 3)
print("Random Array: \n", random_arr)

#identity matrix
identity_matrix = np.eye(4)
#identity_matrix = np.identity(5)
print("Identity Matrix: \n", identity_matrix)

Zero Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Random Array: 
 [[0.45598812 0.21008994 0.56417781]
 [0.70249733 0.20110884 0.71341776]
 [0.24799009 0.10969424 0.49781332]]
Identity Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
#item size
print("Item Size: ", arr.itemsize, "bytes")

#reshape
reshaped_arr = arr.reshape(5, 1)
print("Reshaped Array: \n", reshaped_arr)

Item Size:  8 bytes
Reshaped Array: 
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [5]:
#slicing
sliced_arr = arr[1:4]
print("Sliced Array: ", sliced_arr)

Sliced Array:  [2 3 4]


In [6]:
#line space
linspace_arr = np.linspace(0, 10, 5)
print("Linspace Array: ", linspace_arr)

Linspace Array:  [ 0.   2.5  5.   7.5 10. ]


In [7]:
#max, min, sum, sqrt
print("Max: ", arr.max())
print("Min: ", arr.min())           
print("Sum: ", arr.sum())   
print("Square Root: ", np.sqrt(arr))

Max:  5
Min:  1
Sum:  15
Square Root:  [1.         1.41421356 1.73205081 2.         2.23606798]


In [8]:
#ravel
raveled_arr = arr.ravel()
print("Flattened Array: ", raveled_arr)

Flattened Array:  [1 2 3 4 5]


In [9]:
#shape,data type, size, dimensions,item size, reshape, slicing, linspace, max, min, sum, sqrt, ravel

In [10]:
#basic array operations
#join, split, search, sort, indexing, slicing, iteration, copy, array shape manipulation.

In [11]:
#join - hstack
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[7, 8, 9],[10, 11, 12]])
joined_arr = np.concatenate((arr1, arr2), axis=1)
print("Joined Array: ", joined_arr)

#join vstack
vstack_arr = np.vstack((arr1, arr2))
print("VStacked Array: \n", vstack_arr)

#join hstack    
hstack_arr = np.hstack((arr1, arr2))
print("HStacked Array: ", hstack_arr)

Joined Array:  [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
VStacked Array: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
HStacked Array:  [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [12]:
#split
arr4 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
split_arr = np.split(arr4, 2, axis=1)
print("Split Arrays:", split_arr)

Split Arrays: [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [13]:
search_arr = np.array([10, 20, 30, 40, 50])
index = np.where(search_arr == 30)
print("Index of 30: ", index)

Index of 30:  (array([2]),)


In [14]:
#sort

arr3 = np.array([5, 2, 9, 1, 5, 6])
sorted_arr = np.sort(arr3)
print("Sorted Array: ", sorted_arr)

Sorted Array:  [1 2 5 5 6 9]


In [15]:
#indexing
print("First Element: ", arr[0])
print("Last Element: ", arr[-1])

#slicing
sliced_arr = arr[1:4]
print("Sliced Array: ", sliced_arr)

#iterating
for element in arr:
    print("Element: ", element)

First Element:  1
Last Element:  5
Sliced Array:  [2 3 4]
Element:  1
Element:  2
Element:  3
Element:  4
Element:  5


In [16]:
#copy
copied_arr = arr.copy()
copied_arr[0] = 100
print("Copied Array: ", copied_arr) 
print("Original Array: ", arr)

Copied Array:  [100   2   3   4   5]
Original Array:  [1 2 3 4 5]


In [17]:
#array shape manipulation
reshaped_arr = arr.reshape(5, 1)
print("Reshaped Array: \n", reshaped_arr)

Reshaped Array: 
 [[1]
 [2]
 [3]
 [4]
 [5]]
